### ISSUE TITLE
Project fails to compile with current complier, but there is an easy fix

### ISSUE THREAD

**Issue by 10aded** [michal-z/zig-d3d12-starter#1]
The project fails to build with the current (`0.13.0-dev.267+793f820b3`) Zig compiler. There is an easy fix though.

## The problem:

When attempting compilation, the following error message was generated:

```
C:\Users\10aded\Documents\Michal-Z-Zig-D3D12-Example\build.zig:11:33: error: no field named 'path' in union 'Build.LazyPath'
        .root_source_file = .{ .path = "src/main.zig" },
                                ^~~~
C:\Users\10aded\Zig-Curr\lib\std\Build.zig:2133:22: note: union declared here
pub const LazyPath = union(enum) {
                     ^~~~~
referenced by:
    runBuild__anon_8897: C:\Users\10aded\Zig-Curr\lib\std\Build.zig:2078:27
    main: C:\Users\10aded\Zig-Curr\lib\compiler\build_runner.zig:300:29
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
```

## A Fix:

Replace all the old path structs in `build.zig` like

```.root_source_file = .{ .path = "src/main.zig" },``` (line 13)

with

```.root_source_file = std.Build.path(b, "./src/main.zig"),```

I had to do this 6 times, but I was able to get the project to compile.

**Comment by michal-z** [comment]
Thanks for the info. Fixed.

**Comment by 10aded** [comment]
You're welcome, thanks for the quick repo update!
